// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// addonLazysheepTggoBotDao is the data access object for the table hg_addon_lazysheep_tggo_bot.
// You can define custom methods on it to extend its functionality as needed.
type addonLazysheepTggoBotDao struct {
	*internal.AddonLazysheepTggoBotDao
}

var (
	// AddonLazysheepTggoBot is a globally accessible object for table hg_addon_lazysheep_tggo_bot operations.
	AddonLazysheepTggoBot = addonLazysheepTggoBotDao{internal.NewAddonLazysheepTggoBotDao()}
)

// Add your custom methods and functionality below.
