// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// addonLazysheepTggoNoteItemDao is the data access object for the table hg_addon_lazysheep_tggo_note_item.
// You can define custom methods on it to extend its functionality as needed.
type addonLazysheepTggoNoteItemDao struct {
	*internal.AddonLazysheepTggoNoteItemDao
}

var (
	// AddonLazysheepTggoNoteItem is a globally accessible object for table hg_addon_lazysheep_tggo_note_item operations.
	AddonLazysheepTggoNoteItem = addonLazysheepTggoNoteItemDao{internal.NewAddonLazysheepTggoNoteItemDao()}
)

// Add your custom methods and functionality below.
