// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// addonLazysheepTggoNoteDao is the data access object for the table hg_addon_lazysheep_tggo_note.
// You can define custom methods on it to extend its functionality as needed.
type addonLazysheepTggoNoteDao struct {
	*internal.AddonLazysheepTggoNoteDao
}

var (
	// AddonLazysheepTggoNote is a globally accessible object for table hg_addon_lazysheep_tggo_note operations.
	AddonLazysheepTggoNote = addonLazysheepTggoNoteDao{internal.NewAddonLazysheepTggoNoteDao()}
)

// Add your custom methods and functionality below.
