// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// addonLazysheepTggoNoteAssetDao is the data access object for the table hg_addon_lazysheep_tggo_note_asset.
// You can define custom methods on it to extend its functionality as needed.
type addonLazysheepTggoNoteAssetDao struct {
	*internal.AddonLazysheepTggoNoteAssetDao
}

var (
	// AddonLazysheepTggoNoteAsset is a globally accessible object for table hg_addon_lazysheep_tggo_note_asset operations.
	AddonLazysheepTggoNoteAsset = addonLazysheepTggoNoteAssetDao{internal.NewAddonLazysheepTggoNoteAssetDao()}
)

// Add your custom methods and functionality below.
