// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// addonLazysheepTggoUserDao is the data access object for the table hg_addon_lazysheep_tggo_user.
// You can define custom methods on it to extend its functionality as needed.
type addonLazysheepTggoUserDao struct {
	*internal.AddonLazysheepTggoUserDao
}

var (
	// AddonLazysheepTggoUser is a globally accessible object for table hg_addon_lazysheep_tggo_user operations.
	AddonLazysheepTggoUser = addonLazysheepTggoUserDao{internal.NewAddonLazysheepTggoUserDao()}
)

// Add your custom methods and functionality below.
